import Head from 'next/head'
import {react,useState,useEffect} from 'react'
import Image from 'next/image'
import {Select} from 'antd'
const { Option } = Select;

import Header from './components/header';
//import 'mapbox-gl/dist/mapbox-gl.css';
const mapboxgl = require('mapbox-gl/dist/mapbox-gl.js');
 import Footer from './components/footer';
 import Searchbar from './components/searchbar';
 var axios = require('axios');
export default function Home() {
  const [pageIsMounted, setPageIsMounted] = useState(false)
  useEffect(() => {
    setPageIsMounted(true)
    var map = new mapboxgl.Map({
      container: 'YOUR_CONTAINER_ELEMENT_ID',
      style: 'mapbox://styles/mapbox/streets-v11',
      center: [72.877655,19.075983 ], zoom: 10 ,
    });
}, [])

function handleChange(value) {
  console.log(`selected ${value}`);
}

  mapboxgl.accessToken = 'pk.eyJ1Ijoicml5YW5lc3QiLCJhIjoiY2t2Y2JjNWI4Nm5qaDJvczczMW84YjFzdyJ9._b1tclRVmyGQZmUcoKfKhQ';

  return (
    <div >
      <Head>
        <title>Munaf Property</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
        <link href='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css' rel='stylesheet' />
      </Head>

      <main >
        <Header/>
        <div style={{height:"700px",width:'100%',position:'relative'}}>
          <Searchbar/>
          <div>

            <div style={{height:"500px"}} id="YOUR_CONTAINER_ELEMENT_ID"></div>

          </div>
        </div>

        <br/>

        <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>

      </main>

<Footer/>

    </div>
  )
}
